force-app/main/default/objects/RC_event__c/fields/event_date__c.field-meta.xml
<CustomField>
    <fullName>event_date__c</fullName>
    <label>Event_date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RC_event__c/fields/event_start_time__c.field-meta.xml
<CustomField>
    <fullName>event_start_time__c</fullName>
    <label>Event_start_time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RC_event__c/fields/isTestLive__c.field-meta.xml
<CustomField>
    <fullName>isTestLive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>has the test begun?</description>
    <label>isTestLive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AssignPanelistEventListCtrl.cls
public without sharing class AssignPanelistEventListCtrl {  

    @RemoteAction
    public static List<RC_event__c> GetEventData(){
   
        String query = 'SELECT Id, event_date__c, event_duration__c, event_id__c, event_location__c, event_start_time__c, isTestLive__c, Name FROM RC_event__c';
        
               
        List<RC_event__c> EventList = Database.query(query);
   
        System.debug('*4 '+EventList);
        return EventList;
    } 

 

    @RemoteAction
    public static List<RC_event__c> GetSearchEventsData(String SearchString){
        String query = 'SELECT Id, event_date__c, event_duration__c, event_id__c, event_location__c, event_start_time__c, isTestLive__c, Name FROM RC_event__c WHERE ' +
        ' (Name LIKE \''+'%' + SearchString +'%'+ '\''+' OR '+' event_id__c LIKE \''+'%' + SearchString +'%'+ '\')';
                System.debug('*23 '+query);
        List<RC_event__c> StudetList = Database.query(query); 
        return StudetList;
    }
 
}