force-app/main/default/objects/RC_director__c/RC_director__c.object-meta.xml
<CustomObject>
    <label>RC_director</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>RC_directors Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RC_directors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_director__c/fields/directorEmail__c.field-meta.xml
<CustomField>
    <fullName>directorEmail__c</fullName>
    <description>The email of the director</description>
    <label>directorEmail</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_director__c/fields/directorPassword__c.field-meta.xml
<CustomField>
    <fullName>directorPassword__c</fullName>
    <description>The password</description>
    <label>directorPassword</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_panelist__c/fields/panelistsPassword__c.field-meta.xml
<CustomField>
    <fullName>panelistsPassword__c</fullName>
    <label>panelistsPassword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdminLoginController.cls
public without sharing class AdminLoginController {
    public class LoginDetails{
        public String recordID;
        public Boolean isAdmin;
        public Boolean isDirector;
        public LoginDetails(String recordID,Boolean isAdmin, Boolean isDirector){
            this.recordID = recordID;
            this.isAdmin = isAdmin;
            this.isDirector = isDirector;
        }
    }

    @RemoteAction
    public static LoginDetails LoginAdmin(String EmailInput, String adminPassword) {

            List<RC_panelist__c> panelistRes = [SELECT Id, panelistsEmail__c FROM RC_panelist__c WHERE panelistsEmail__c = :EmailInput AND panelistsPassword__c = :adminPassword];
            List<RC_admin__c> adminRes = [SELECT Id, adminEmail__c FROM RC_admin__c WHERE adminEmail__c = :EmailInput AND adminPassword__c = :adminPassword];
            List<RC_director__c> directorRes = [SELECT Id, directorEmail__c FROM RC_director__c WHERE directorEmail__c = :EmailInput AND directorPassword__c = :adminPassword];
            
            if(adminRes.size() != 0)
            {
                LoginDetails lg = new LoginDetails(adminRes[0].Id,true,false);
                return lg;
            }

            if(panelistRes.size() != 0)
            {
                LoginDetails lg = new LoginDetails(panelistRes[0].Id,false,false);
                return lg;
            }

            if(directorRes.size() != 0)
            {
                LoginDetails lg = new LoginDetails(directorRes[0].Id,false,true);
                return lg;
            }

            if(adminRes.size() == 0 && panelistRes.size() == 0 && directorRes.size() == 0)
            {
                LoginDetails lg = new LoginDetails('',false,false);
                return lg;
            }

            return null;
       }
    
}